### ISSUE TITLE
Easy confident CHT upgrades for apps

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-roadmap#66] opened 2021-12-12 22:13 UTC
**Overview**
CHT apps sometimes fall out-of-date and miss out on new features, technical improvements, and other enhancements. Upgrading the CHT should be easy to do in a manner that brings confidence to project members.

- [ ] Updated opportunity solution tree
- [ ] Solution story maps
- [ ] Solution selection
- [ ] Assumption investigation
- [ ] Development
- [ ] Deployment

**Comment by Reagan** [comment] 2023-07-18 18:23
Duplicate of [this](https://github.com/medic/cht-roadmap/issues/92 ) cc @craig-landry

**Closed by Reagan** 2023-07-18 18:23 UTC
Labels: strat: CHT is easy for app builders to work with
