### ISSUE TITLE
Enhanced CHT system monitoring and error detection

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-roadmap#62] opened 2021-12-12 22:12 UTC
**Overview**
Issues with CHT systems can be difficult to identify and debug. Engineers troublshooting issues should be able to easily notice issues and have them resolved quickly.

**Comment by garethbowen** [comment] 2023-04-03 02:33
Duplicate of #85

**Closed by garethbowen** 2023-04-03 02:33 UTC
Labels: strat: Make server components reliable under load
